In [1]:
import numpy as np
import cv2 as cv
# import video
import sys
if __name__ == '__main__':
#      try:
#          video_src = sys.argv[1]
#      except:
#          video_src = 0
    cam = cv.VideoCapture(0)
#      cam = video.create_capture(video_src)
    mser = cv.MSER_create()
    while True:
        ret, img = cam.read()
        if ret == 0:
            break
        gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
        vis = img.copy()
        regions, _ = mser.detectRegions(gray)
        hulls = [cv.convexHull(p.reshape(-1, 1, 2)) for p in regions]
        cv.polylines(vis, hulls, 1, (0, 255, 0))
 
        cv.imshow('img', vis)
        if cv.waitKey(5) == 27:
            break
    cv.destroyAllWindows()

In [1]:
import numpy as np
import cv2 as cv
# import video
import sys

if __name__ == '__main__':
    mser = cv.MSER_create()
#     img = cv.imread("images/hindi.jpg")
#     img = cv.imread("images/final.jpg")
    img = cv.imread("python-swt/final3.jpg")
    vis = img.copy()
    gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
    regions, bboxes = mser.detectRegions(gray)
    hulls = [cv.convexHull(p.reshape(-1, 1, 2)) for p in regions]
    cv.polylines(vis, hulls, 1, (0, 255, 0))
    print("vis : ", type(vis))
    cv.imshow('img', vis)
    cv.imwrite("mser11.jpg", vis)
    i=0
    name = str(i)
    for p in regions:
        vis = img.copy()
        hull = cv.convexHull(p.reshape(-1, 1, 2))
        cv.polylines(vis, hull, 1, (0, 255, 0))
#         print(hull)
#         print(type(hull))
#         print(type(p))
        print(p)
        cv.imwrite("regions" + str(i)+".jpg", vis)
        i+=1
        print(i)

#     for p in bboxes:
#         vis = img.copy()
#         print(p)
#         print("next")
#         cv.rectangle(vis, (p[0], p[1]), (p[2], p[3]), (0, 255, 0))
#         cv.imwrite(str(i)+".jpg", vis)
#         i+=1
#         print(i)

#     print(img[0:100][0:100])
#     for p in bboxes:
#         print(p)
#         a = p[0]
#         b = p[0]+p[2]
#         c = p[1]
#         d = p[1]+p[3]
#         print(a, " ", b, " ", c, " ", d)
# #         cv.imwrite(str[i]+".jpg", img[p[0]:p[0]+p[2]] [p[1]:p[1]+p[3]])
# #         cv.imwrite(str[i]+".jpg", img[a:b][c:d])
#         cv.imwrite(str(i)+"final.jpg", img[a:c][b:d])
#         cv.waitKey(0)
#         i+=1
cv.waitKey(0)
cv.destroyAllWindows()

vis :  <class 'numpy.ndarray'>
[[215 229]
 [217 229]
 [216 228]
 ...
 [228 236]
 [229 214]
 [217 207]]
1
[[471 292]
 [472 291]
 [473 290]
 ...
 [483 299]
 [473 276]
 [493 315]]
2
[[554 278]
 [554 277]
 [553 277]
 [554 279]
 [554 280]
 [553 280]
 [553 281]
 [553 282]
 [553 283]
 [553 284]
 [553 285]
 [553 286]
 [553 287]
 [553 288]
 [553 289]
 [553 290]
 [553 291]
 [553 292]
 [553 293]
 [553 294]
 [553 295]
 [553 296]
 [553 297]
 [553 298]
 [553 299]
 [553 300]
 [553 301]
 [553 302]
 [553 303]
 [553 304]
 [553 305]
 [553 306]
 [553 307]
 [553 308]
 [553 309]
 [553 310]
 [553 311]
 [554 311]
 [555 311]
 [555 310]
 [555 309]
 [555 308]
 [555 307]
 [555 306]
 [555 305]
 [555 304]
 [555 303]
 [555 302]
 [555 301]
 [555 300]
 [555 299]
 [555 298]
 [555 297]
 [555 296]
 [555 295]
 [555 294]
 [555 293]
 [555 292]
 [555 291]
 [555 290]
 [555 289]
 [555 288]
 [555 287]
 [555 286]
 [555 285]
 [555 284]
 [555 283]
 [555 282]
 [555 281]
 [556 281]
 [556 280]
 [556 279]
 [556 278]
 [556 277]
 [556 2

[[619 120]
 [620 120]
 [621 120]
 [623 120]
 [624 120]
 [625 120]
 [626 120]
 [627 120]
 [628 120]
 [629 120]
 [630 120]
 [631 120]
 [632 120]
 [633 120]
 [634 120]
 [635 120]
 [636 120]
 [637 120]
 [638 120]
 [639 120]
 [640 120]
 [641 120]
 [642 120]
 [643 120]
 [644 120]
 [645 120]
 [646 120]
 [647 120]
 [648 120]
 [649 120]
 [650 120]
 [651 120]
 [652 120]
 [653 120]
 [654 120]
 [655 120]
 [656 120]
 [657 120]
 [658 120]
 [659 120]
 [660 120]
 [661 120]
 [662 120]
 [663 120]
 [664 120]
 [665 120]
 [666 120]
 [667 120]
 [668 120]
 [669 120]
 [670 120]
 [671 120]
 [672 120]
 [673 120]
 [674 120]
 [675 120]
 [676 120]
 [677 120]
 [678 120]
 [679 120]
 [680 120]
 [622 120]]
11
[[614 166]
 [613 166]
 [612 166]
 [611 166]
 [610 166]
 [609 166]
 [608 166]
 [607 166]
 [606 166]
 [605 166]
 [604 166]
 [603 166]
 [602 166]
 [601 166]
 [600 166]
 [599 166]
 [598 166]
 [597 166]
 [596 166]
 [595 166]
 [594 166]
 [593 166]
 [592 166]
 [591 166]
 [615 166]
 [616 166]
 [617 166]
 [618 166]
 [619 

20
[[322 283]
 [323 283]
 [324 283]
 [324 282]
 [324 281]
 [323 281]
 [323 280]
 [323 279]
 [323 278]
 [323 277]
 [323 276]
 [322 278]
 [321 278]
 [322 280]
 [324 284]
 [325 284]
 [325 285]
 [325 286]
 [326 284]
 [326 283]
 [326 282]
 [326 281]
 [326 280]
 [325 280]
 [325 279]
 [327 282]
 [327 284]
 [327 285]
 [328 284]
 [329 284]
 [329 283]
 [329 282]
 [330 284]
 [330 285]
 [331 285]
 [331 286]
 [331 287]
 [331 288]
 [330 288]
 [330 289]
 [329 289]
 [328 289]
 [328 288]
 [328 287]
 [327 287]
 [326 287]
 [326 288]
 [326 289]
 [326 290]
 [326 291]
 [326 292]
 [326 293]
 [326 294]
 [326 295]
 [327 295]
 [327 296]
 [328 296]
 [328 297]
 [328 298]
 [327 298]
 [327 299]
 [326 299]
 [326 300]
 [326 301]
 [326 302]
 [328 299]
 [328 300]
 [328 301]
 [328 302]
 [328 303]
 [327 303]
 [328 304]
 [328 305]
 [327 305]
 [326 305]
 [326 304]
 [326 306]
 [328 306]
 [328 307]
 [327 307]
 [327 308]
 [328 308]
 [328 309]
 [328 310]
 [327 310]
 [326 310]
 [326 311]
 [328 311]
 [328 312]
 [327 312]
 [327 3

[[  1 168]
 [  1 169]
 [  1 170]
 [  1 171]
 [  1 172]
 [  1 173]
 [  1 174]
 [  1 175]
 [  1 176]
 [  1 177]
 [  2 176]
 [  2 175]
 [  3 175]
 [  3 174]
 [  3 173]
 [  3 172]
 [  3 171]
 [  3 170]
 [  3 169]
 [  3 168]
 [  4 168]
 [  5 168]
 [  5 169]
 [  5 170]
 [  5 171]
 [  5 172]
 [  5 173]
 [  5 174]
 [  5 175]
 [  5 176]
 [  4 176]
 [  4 177]
 [  3 177]
 [  5 177]
 [  6 176]
 [  6 175]
 [  7 175]
 [  7 174]
 [  7 173]
 [  7 172]
 [  7 171]
 [  7 170]
 [  7 169]
 [  7 168]
 [  8 168]
 [  9 168]
 [  9 169]
 [  9 170]
 [  9 171]
 [  9 172]
 [  9 173]
 [  9 174]
 [  9 175]
 [  9 176]
 [  8 176]
 [  8 177]
 [  7 177]
 [  9 177]
 [ 10 177]
 [ 11 177]
 [ 11 176]
 [ 11 175]
 [ 11 174]
 [ 11 173]
 [ 11 172]
 [ 11 171]
 [ 11 170]
 [ 11 169]
 [ 11 168]
 [ 12 168]
 [ 13 168]
 [ 13 169]
 [ 13 170]
 [ 13 171]
 [ 13 172]
 [ 13 173]
 [ 13 174]
 [ 13 175]
 [ 13 176]
 [ 13 177]
 [ 14 177]
 [ 15 177]
 [ 15 176]
 [ 15 175]
 [ 15 174]
 [ 15 173]
 [ 15 172]
 [ 15 171]
 [ 15 170]
 [ 15 169]
 [ 15 168]

In [3]:
import cv2

img = cv2.imread("images/hindi.jpg")

sift = cv2.xfeatures2d.SIFT_create()

AttributeError: module 'cv2.cv2' has no attribute 'xfeatures2d'

In [3]:
# import pillowfight
from PIL import Image
from PIL import swt
import cv2
import numpy

input_image = Image.open("test.jpg")
output_img = swt(input_image)
im = numpy.asarray(output_img)
cv2.imwrite('ouut.jpg', im)
print(output_img)

ImportError: cannot import name 'swt'